[package]
name = "helpers"
edition.workspace = true
version.workspace = true

[lib]

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
account_factory = { path = "../account_factory" }

[dev-dependencies]
snforge_std.workspace = true
starkware_utils_testing.workspace = true
testing_utils = { path = "../testing_utils" }

[[target.starknet-contract]]
sierra = true
casm = true

[[test]]
build-external-contracts = [
    "contracts::primer::primer::Primer",
    "testing_utils::dummy_contracts::DummyEthAddressContract",
    "testing_utils::dummy_contracts::SecondDummyEthAddressContract",
    "testing_utils::dummy_contracts::MockOutsideExecutionTarget",
    "account_factory::account_factory::AccountFactory",
]
name = "helpers_unittest"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[scripts]
test = "snforge test"
