[package]
name = "testing_utils"
edition.workspace = true
version.workspace = true

[lib]

[dependencies]
account_factory = { path = "../account_factory" }
contracts = { path = "../contracts" }
openzeppelin.workspace = true
snforge_std.workspace = true
starknet.workspace = true
starkware_utils.workspace = true
starkware_utils_testing.workspace = true

[[target.starknet-contract]]
sierra = true

[[test]]
name = "testing_utils_unittest"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[scripts]
test = "snforge test"
