use snforge_std::{ContractClassTrait, DeclareResultTrait};
use starknet::secp256_trait::Signature;
use starknet::{ClassHash, ContractAddress, EthAddress, SyscallResultTrait};

/// Test Ethereum address corresponding to private key:
/// 0xa6d86467b6ec9e161649b27edfd8519e75a2e1cf5f4c309c628706e6999780e8
/// Address: 0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A
pub fn TEST_ETH_ADDRESS() -> EthAddress {
    0xbF60187c5dFfA627249f1C3000A4168dbB9D7A1A_felt252.try_into().unwrap()
}

/// A different Ethereum address for testing invalid cases.
pub fn WRONG_ETH_ADDRESS() -> EthAddress {
    0x1234567890123456789012345678901234567890_felt252.try_into().unwrap()
}

/// Returns the ownership signature for TEST_ETH_ADDRESS.
/// This signature was generated by signing the OWNERSHIP_TRANSFER_MSG_HASH
/// (0x3ce976d55131cd0bdd49f20afbded052d8e907dc6034d95cdf117a8fd7752e3c)
/// with the test private key.
///
/// Values from: split_raw_eth_sig_to_felts output
/// '0xda47d5165a4577a024d18b8d61c5fe53 0xe994c0e202b390bddaffacf04bdea826
/// 0x46dd0af587023ccad738aa0a82b05f98 0x2e117624d8cc474d0641c3168944eb67 0x1'
pub fn get_ownership_signature() -> Signature {
    Signature {
        r: u256 {
            low: 0xda47d5165a4577a024d18b8d61c5fe53, high: 0xe994c0e202b390bddaffacf04bdea826,
        },
        s: u256 {
            low: 0x46dd0af587023ccad738aa0a82b05f98, high: 0x2e117624d8cc474d0641c3168944eb67,
        },
        y_parity: true // v % 2 == 0
    }
}

/// Returns an invalid signature for testing.
pub fn get_invalid_signature() -> Signature {
    Signature {
        r: u256 { low: 0x1234567890abcdef, high: 0xfedcba0987654321 },
        s: u256 { low: 0xabcdef1234567890, high: 0x1234567890abcdef },
        y_parity: false,
    }
}

/// Declare and deploy the StarknetEth712Account contract.
/// Returns the contract address and the class hash.
pub fn deploy_eth712_account() -> (ContractAddress, ClassHash) {
    let contract_class = snforge_std::declare("StarknetEth712Account")
        .unwrap_syscall()
        .contract_class();
    let (contract_address, _) = contract_class.deploy(@array![]).unwrap_syscall();
    (contract_address, *contract_class.class_hash)
}

/// Declare the RegisterInterfacesEIC contract and return its class hash.
pub fn declare_register_interfaces_eic() -> ClassHash {
    *snforge_std::declare("RegisterInterfacesEIC").unwrap_syscall().contract_class().class_hash
}
