[package]
name = "eth_712_account"
edition.workspace = true
version.workspace = true

[dependencies]
openzeppelin.workspace = true
starknet.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
