[package]
name = "contracts"
edition.workspace = true
version.workspace = true

[lib]

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
starkware_utils_testing.workspace = true

[[target.starknet-contract]]
sierra = true

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[scripts]
test = "snforge test"
