[package]
name = "earn_reporter"
edition.workspace = true
version.workspace = true

[lib]

[dependencies]
openzeppelin.workspace = true
openzeppelin_upgrades.workspace = true
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true
starkware_utils_testing.workspace = true
testing_utils = { path = "../testing_utils" }

[[target.starknet-contract]]
sierra = true

[[test]]
build-external-contracts = [
    "testing_utils::dummy_contracts::DummyEthAddressContract",
]
name = "earn_reporter_unittest"

[profile.dev.cairo]
unstable-add-statements-functions-debug-info = true
unstable-add-statements-code-locations-debug-info = true
inlining-strategy = "avoid"

[scripts]
test = "snforge test"
